{% set name = "lb-nightly-scheduler" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-scheduler-{{ version }}.tar.gz
  sha256: 509dc1d6f738862e1125fc3becce80c4c9d3e4810771ca691cbeb23b7f723aeb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - gitpython >=3.1.18,<4.0.0
    - lb-nightly-configuration >=0.3,<1.0
    - lb-nightly-db >=0.2,<1.0
    - lb-nightly-rpc >=0.2,<1.0
    - lb-nightly-utils >=0.4,<1.0
    - luigi >=3.0.3,<4.0.0
    - python >=3.6,<4.0

test:
  imports:
    - lb
    - lb.nightly.scheduler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/nightly-builds/lb-nightly-scheduler
  summary: Scheduler implementation for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pikacic
    - maszyman
